# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bcbc8a88fb8cdb8f271a71580fb2e8a42e030701b254e5e6fdf3b8650ef54dc9277ea08c9268b856acd0ffb440e19bd75fb557fae7f6c5fff1d02e3268d40cfe

test:
  secret_key_base: b4d71180a9cd93a97dbdd29bf081aa40ab0837543468e441792323e434e6e5d55c8a37cb17d05ec8c0279b6088bd874d5398321dc59e2a070777899cd50f2905

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
